version: "2.3"

networks:
  yemusic:
    driver: bridge

services:
  web-app:
    container_name: yemusic-webapp
    image: vc-yemusic:web-app
    build:
      context: ./
      dockerfile: ./apps/web/Dockerfile
      cache_from:
        - nginx:alpine
    ports:
      - 4900:80
  web-storybook:
    container_name: yemusic-storybook
    image: vc-yemusic:web-storybook
    build:
      context: ./
      dockerfile: ./apps/web/.storybook/Dockerfile
      cache_from:
        - nginx:alpine
    ports:
      - 4901:80
  mongodb:
    image: mongo:4.2-bionic
    container_name: yemusic-mongodb
    ports:
      - 4800:27017
    environment:
      - MONGO_INITDB_DATABASE=yemusic
      - MONGO_INITDB_ROOT_USERNAME=vcteam
      - MONGO_INITDB_ROOT_PASSWORD=vcteam1122
    volumes:
      - /var/vcteam/yemusic/db/mongodb/data:/data/db
      - /var/vcteam/yemusic/db/mongodb/config:/data/configdb
    networks:
      - yemusic
  redis:
    image: redis
    container_name: yemusic-redis
    restart: always
    ports: 
      - '6390:6379'
    volumes:
      - /var/vcteam/yemusic/db/redis:/data/redis
      - /var/vcteam/yemusic/db/redis/redis.conf:/data/redis.conf
    environment:
      - REDIS_PORT=${YEMUSIC_API_SERVER_REDIS_PORT:-6379}
      - REDIS_UERNAME=${YEMUSIC_API_SERVER_REDIS_UERNAME:-redis}
      - REDIS_PASSWORD=${YEMUSIC_API_SERVER_REDIS_PASSWORD:-vcteam6379}
      - REDIS_DB=${YEMUSIC_API_SERVER_REDIS_DB:-0}
  server-api:
    container_name: yemusic-server-api
    image: vc-yemusic:server-api
    build:
      context: ./
      dockerfile: ./apps/server/Dockerfile
    environment:
      - API_PORT=$YEMUSIC_API_SERVER_PORT
      - DB_HOST=mongodb
      - DB_DEFAULT=db_yemusic
      - NODEMAILER_HOST=${YEMUSIC_API_SERVER_HOST:-smtp.gmail.com}
      - NODEMAILER_PORT=${YEMUSIC_API_SERVER_NODEMAILER_PORT:-587}
      - NODEMAILER_USERNAME=${YEMUSIC_API_SERVER_NODEMAILER_USERNAME:-demo@gmail.com}
      - NODEMAILER_PASSWORD=${YEMUSIC_API_SERVER_NODEMAILER_PASSWORD:-demo1212}
      - DB_USERNAME=${YEMUSIC_API_SERVER_DB_USERNAME:-vcteam}
      - DB_PASSWORD=${YEMUSIC_API_SERVER_DB_PASSWORD:-vcteam1122}
      - REDIS_HOST=redis
      - REDIS_PORT=${YEMUSIC_API_SERVER_REDIS_PORT:-6379}
      - REDIS_UERNAME=${YEMUSIC_API_SERVER_REDIS_UERNAME:-redis}
      - REDIS_PASSWORD=${YEMUSIC_API_SERVER_REDIS_PASSWORD:-vcteam6379}
      - REDIS_DB=${YEMUSIC_API_SERVER_REDIS_DB:-0}
    ports:
      - 4902:$YEMUSIC_API_SERVER_PORT
    networks:
      - yemusic
    depends_on:
      - mongodb
      - redis

