name: CI Develop
on:
  pull_request:
    branches:
      - develop

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npx nx affected --target=lint --base=origin/develop --parallel=2

      - name: Test
        run: npx nx affected --target=test --base=origin/develop --parallel=2
