name: Release Docker Image & Deploying

on:
  push:
    branches: [feat/docker-setup]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      
      - name: Create env file
        run: |
          touch .env
          echo YEMUSIC_API_SERVER_PORT={{ secrets.YEMUSIC_API_SERVER_PORT }} >> .env

      - name: Build base image
        run: docker build . -t vc-yemusic:base
    
      - name: Build app images
        run: docker compose -f docker-compose.yml build

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Images
        run: docker compose -f docker-compose.yml push
