name: Release Docker Image & Deploying

on:
  push:
    branches: [feat/docker-setup]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create env file
        run: |
          touch .env
          echo YEMUSIC_API_SERVER_PORT=${{ secrets.YEMUSIC_API_SERVER_PORT }} >> .env
      - name: Caching Layer
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build the base image
        run: docker build . -t vc-yemusic:base

      - name: Build the app images
        run: docker compose -f docker-compose.yml build

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Images
        run: | 
          docker tag vc-yemusic:server-api ${{ secrets.DOCKERHUB_USERNAME }}/vc-yemusic:server-api
          docker tag vc-yemusic:web-app ${{ secrets.DOCKERHUB_USERNAME }}/vc-yemusic:web-app
          docker tag vc-yemusic:web-storybook ${{ secrets.DOCKERHUB_USERNAME }}/vc-yemusic:web-storybook

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vc-yemusic:server-api
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vc-yemusic:web-app
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/vc-yemusic:web-storybook

      - name: Remove Dangling Images
        run: docker rmi $(docker images -f dangling=true -q)

  deploy:
    needs:
      - build-docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Copy compose file via password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.prod.yml"
          target: "~/apps/vc-yemusic"

      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        env:
          YEMUSIC_API_SERVER_PORT: ${{ secrets.YEMUSIC_API_SERVER_PORT }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        with:
          host: '${{ secrets.SSH_HOST }}'
          username: '${{ secrets.SSH_USERNAME }}'
          key: '${{ secrets.SSH_KEY }}'
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: '${{ secrets.SSH_PORT }}'
          script: |
            cd ~/apps/vc-yemusic
            YEMUSIC_API_SERVER_PORT=$YEMUSIC_API_SERVER_PORT DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME docker-compose -f docker-compose.prod.yml up -d --no-deps
