name: Release Docker Image & Deploying

on:
  push:
    branches: [feat/docker-setup]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: Cache Docker layers
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Create env file
        run: |
          touch .env
          echo YEMUSIC_API_SERVER_PORT=${{ secrets.YEMUSIC_API_SERVER_PORT }} >> .env
      - name: Caching Layer
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build the base image
        run: docker build . -t vc-yemusic:base

      - name: Build the app images
        run: docker compose -f docker-compose.yml build

      - name: List images
        run: docker image ls

      # - name: Build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     load: true
      #     tags: vc-yemusic:base
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache-new

      # - name: Build app images
      #   run: docker compose -f docker-compose.yml build

      # - name: Push Docker Images
      #   run: | 
      #     docker compose -f docker-compose.yml push
      #     docker push vc-yemusic:base

      # - name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache
